on:
  workflow_dispatch:
    inputs:
      lre_domain:
        description: 'Domain'
        required: true
        default: 'DEFAULT'
      lre_project:
        description: 'Project'
        required: true
        default: 'advantageonlineshopping'
      lre_test:
        description: 'Test ID'
        required: true
      lre_test_output_dir:
        description: 'The directory to save test run results'
        required: true
        default: 'LRE-Test-'
jobs:
  test:
    runs-on: self-hosted
    name: LRE-Execute-Load-Test 
    env:
      lre_username: ${{ secrets.LRE_USERNAME }}
      lre_password: ${{ secrets.LRE_PASSWORD }}    
    steps:
      - name: LRE-Run-Test
        uses: MicroFocus/lre-gh-action@v1.0.2
        id: lre_run_test
        with:
          lre_enable_stacktrace : true       
          lre_action: ExecuteLreTest
          lre_description: Run load test in LRE
          lre_server: nimbuswindows.emea.softwaregrp.net
          lre_https_protocol: false
          lre_authenticate_with_token: true
          lre_domain: ${{ github.event.inputs.lre_domain }}
          lre_project: ${{ github.event.inputs.lre_project }}
          lre_test: ${{ github.event.inputs.lre_test }}
          lre_test_instance: AUTO
          lre_timeslot_duration_hours: 0
          lre_timeslot_duration_minutes: 15
          lre_post_run_action: 'Collate and Analyze'
          lre_vuds_mode: false
          lre_status_by_sla: false
          lre_output_dir: ${{ github.workspace }}
      - name: Upload LRE results
        uses: actions/upload-artifact@v4
        id: lre_upload_test_result
        with:
          name: LRE-Load-Test-Result
          path: ${{ github.workspace }}/LreResult
          
