on:
    workflow_dispatch:
      inputs:
      lre_server:
        description: 'LRE URL'
        required: true
        default: 'nimbuswindows.emea.softwaregrp.net'
      lre_domain:
        description: 'Domain'
        required: true
        default: 'DEFAULT'
      lre_project:
        description: 'Project'
        required: true
        default: 'advantageonlineshopping'
      lre_test:
        description: 'Test ID'
        required: true
      lre_output_dir:
        description: 'The directory to save results'
        required: false
        default: './LreResult'
      lrc_report_types:
        description: 'Target report types. For example: pdf, docx, csv'
        required: false
        default: 'pdf'
jobs:
  start_load_test:
    runs-on: self-hosted
    name: Execute LRE load test   
    steps:
      - name: Run test in LRE
        uses: MicroFocus/lre-gh-action@v1.0.2
        id: lre_run_test
        env:
            lre_username: ${{ secrets.LRE_APIKey_ClientId }}
            lre_password: ${{ secrets.LRE_APIKey_ClientSecret }}
        with:
          lre_action: ExecuteLreTest
          lre_description: Run load test in LRE
          lre_server: nimbuswindows.emea.softwaregrp.net
          lre_https_protocol: false
          lre_authenticate_with_token: true
          lre_domain: DEFAULT
          lre_project: advantageonlineshopping
          lre_test: 198
          lre_test_instance: AUTO
          lre_timeslot_duration_hours: 0
          lre_timeslot_duration_minutes: 15
          lre_post_run_action: Collate and Analyze
          lre_vuds_mode: false
          lre_trend_report: ASSOCIATED
          lre_status_by_sla: false
          lre_output_dir: ${{ github.workspace }}

      - name: Upload LRE results
        uses: actions/upload-artifact@v4
        with:
          name: LRE Load Test Result
          path: ${{ github.workspace }}/LreResult
          
